### ISSUE TITLE
Value "-33" of type "string" is not suitable for value type "Numeric (unsigned)"

### ISSUE THREAD

**Issue by denisgolius** [areytsman/zabbix_ssl_template#1]
![screenshot](https://user-images.githubusercontent.com/5650611/51121653-9c312f80-1820-11e9-88d4-aea26f61b6f9.png)

alloy-mosaic.com

**Comment by areytsman** [comment]
The certificate is expired 33 days ago. 
I'm made a hotfix to show value "0" instead of negative values.
