### ISSUE TITLE
Is there a tweak to get SSL expiration dates from web scenarios?

### ISSUE THREAD

**Issue by psanwald** [areytsman/zabbix_ssl_template#3]
Hello, 
Iam using this script to get the expiration days from servers. It works very good. But in most constellations the certificates of the servers are different than the certificates of the websites on them. I track these sites with web scenarios in zabbix. Is there a way to let the scipt also discover and track the expiration dates of the web scenarios on a server with this template? I know I can change the ports in the python file, but the sites are name-based and the webservers are all listening on the standard ports. 
Best regards, Pascal

**Comment by areytsman** [comment]
Hi Pascal!
Can you give me an example site for testing? I'll try to improve the script.

**Comment by psanwald** [comment]
Hello Areytsman,
I appreciate it. Any web scenario using https will do. I think you could even create google or ebay as a web scenario for testing purpose.
Best Regards,
Pascal

**Comment by areytsman** [comment]
I can do what you want, but changes will break getting an untrusted certificates. If it isnt yours scenario, replase ssl_expiration_check.py script with ssl_expiration_check_sni.py
